import { describe, it, expect } from 'vitest';
import { readFileSync } from 'fs';
import { resolve } from 'path';
import { TraceOutputSchema } from './schema';

describe('Shared Contract Validation', () => {
  it('should successfully parse the valid trace fixture generated by Python', () => {
    // Read the shared fixture from the root of the repo
    const fixturePath = resolve(__dirname, '../../../shared/fixtures/trace_valid.json');
    const rawData = readFileSync(fixturePath, 'utf-8');
    const data = JSON.parse(rawData);

    // Validate using Zod schema
    // If this fails, the TypeScript schema has drifted from the Python schema
    const result = TraceOutputSchema.safeParse(data);
    
    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data.metadata.algorithm).toBe('PingPong');
      expect(result.data.trace.length).toBe(3);
    }
  });

  it.each([
    'trace_invalid_negative_time.json',
    'trace_invalid_truncation.json'
  ])('rejects invalid shared fixture %s', fixtureName => {
    const fixturePath = resolve(__dirname, '../../../shared/fixtures', fixtureName);
    const data = JSON.parse(readFileSync(fixturePath, 'utf-8'));

    expect(TraceOutputSchema.safeParse(data).success).toBe(false);
  });
});
