name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-core:
    name: Verificar Python Core
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4
      
      - name: Instalar 'uv' (Gestor de Python)
        uses: astral-sh/setup-uv@v5
        
      - name: Instalar dependencias del core
        run: uv sync
        working-directory: ./core

  build-web:
    name: Compilar Dashboard (Next.js)
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4
      
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./web/package-lock.json
          
      - name: Instalar dependencias web
        run: npm ci
        working-directory: ./web
        
      - name: Compilar la web (Build & Lint)
        run: npm run build
        working-directory: ./web
